//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organopedia3.Resources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Organopedia3.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu O aplikacji.
        /// </summary>
        internal static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ułatwienia dostępu.
        /// </summary>
        internal static string Accessibility {
            get {
                return ResourceManager.GetString("Accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Traktury.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Traktura to system mechanicznego, pneumatycznego lub elektrycznego połączenia między klawiaturą a zaworami wiatrownicy, który umożliwia przekazanie polecenia od organisty do piszczałek. Innymi słowy, traktura decyduje o tym, które piszczałki mają zabrzmieć po naciśnięciu odpowiedniego klawisza. W organach wyróżnia się trzy podstawowe typy traktury: Traktura mechaniczna (gryfowa) – oparta na dźwigniach, drążkach i cięgnach, daje bezpośrednie, fizyczne połączenie między klawiszem a zaworem. Ceniona za precyzy [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string ActionsDescription {
            get {
                return ResourceManager.GetString("ActionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer maximus turpis semper erat laoreet, eu viverra est porttitor. Donec mattis vel felis ut rutrum. Morbi eu finibus massa. Donec porttitor metus ut felis rhoncus lacinia. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec nec velit arcu. Vestibulum ac luctus velit. Duis blandit quis magna sit amet venenatis. Vestibulum et commodo quam. Praesent porttitor, elit sed vestibulum viverra, neque libero congue n [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Miechy.
        /// </summary>
        internal static string Bellows {
            get {
                return ResourceManager.GetString("Bellows", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Miech to element organów odpowiedzialny za dostarczanie i utrzymywanie odpowiedniego ciśnienia powietrza (wiatru) potrzebnego do brzmienia piszczałek. Tradycyjnie miechy miały formę dużych, skórzanych worków rozciąganych ręcznie lub nożnie, jednak we współczesnych organach powietrze wtłaczane jest zazwyczaj przez elektryczne dmuchawy, a miechy pełnią funkcję regulatorów ciśnienia i magazynów powietrza. Wyróżnia się różne typy miechów, m.in. miechy klinowe, pudełkowe oraz pływakowe, z których każdy ma inną k [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string BellowsDescription {
            get {
                return ResourceManager.GetString("BellowsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmień rozmiar czcionki.
        /// </summary>
        internal static string ChangeFontSize {
            get {
                return ResourceManager.GetString("ChangeFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Użyj tego pola, by zmienić rozmiar czcionki w aplikacji.
        /// </summary>
        internal static string ChangeFontSizeHelp {
            get {
                return ResourceManager.GetString("ChangeFontSizeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmień język.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Przycisk zmiany języka.
        /// </summary>
        internal static string ChangeLanguageButton {
            get {
                return ResourceManager.GetString("ChangeLanguageButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Użyj tego przycisku, by zmienić język używany w aplikacji.
        /// </summary>
        internal static string ChangeLanguageButtonHelp {
            get {
                return ResourceManager.GetString("ChangeLanguageButtonHelp", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmień motyw.
        /// </summary>
        internal static string ChangeMotiff {
            get {
                return ResourceManager.GetString("ChangeMotiff", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Przycisk zmiany motywu.
        /// </summary>
        internal static string ChangeMotiffButton {
            get {
                return ResourceManager.GetString("ChangeMotiffButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kliknij, by zmienić motyw wizualny aplikacji.
        /// </summary>
        internal static string ChangeMotiffButtonHelp {
            get {
                return ResourceManager.GetString("ChangeMotiffButtonHelp", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wiatrownica skrzyniowa.
        /// </summary>
        internal static string ChestWindchest {
            get {
                return ResourceManager.GetString("ChestWindchest", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wiatrownica skrzyniowa to typ wiatrownicy, w której klapy zaworowe są umieszczone na całej powierzchni, bez podziału na tony czy rejestry. Powietrze dostaje się do wiatrownicy przez otwory, a każda piszczałka ma swoją osobną klapę, którą otwiera naciśnięcie odpowiedniego klawisza. Tego typu wiatrownica jest prostą konstrukcją, stosowaną w mniej skomplikowanych organach, zapewniającą jednak równomierne dostarczanie powietrza do piszczałek..
        /// </summary>
        internal static string ChestWindchestDescription {
            get {
                return ResourceManager.GetString("ChestWindchestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Traktura elektryczna.
        /// </summary>
        internal static string ElectricAction {
            get {
                return ResourceManager.GetString("ElectricAction", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Traktura elektryczna przesyła sygnały z klawiatury do zaworów wiatrownicy za pomocą impulsów elektrycznych. Naciśnięcie klawisza uruchamia obwód, który otwiera odpowiedni zawór pod piszczałką. Umożliwia dużą swobodę w rozmieszczeniu stołu gry, szybki przekaz i stosowanie nowoczesnych funkcji, ale zależy od zasilania i jest bardziej złożona technicznie..
        /// </summary>
        internal static string ElectricActionDescription {
            get {
                return ResourceManager.GetString("ElectricActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Miech pływakowy.
        /// </summary>
        internal static string FloatBellows {
            get {
                return ResourceManager.GetString("FloatBellows", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Miech pływakowy to poziomy zbiornik powietrza z ruchomą górną płytą, która unosi się pod wpływem sprężonego powietrza i opada, gdy jest ono zużywane. Utrzymuje stałe ciśnienie dzięki obciążeniu płyty ciężarami lub sprężynami. Stosowany głównie w nowoczesnych organach z dmuchawą elektryczną, zapewnia dużą pojemność i równomierny przepływ powietrza..
        /// </summary>
        internal static string FloatBellowsDescription {
            get {
                return ResourceManager.GetString("FloatBellowsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Miech horyzontalny.
        /// </summary>
        internal static string HorizontalBellows {
            get {
                return ResourceManager.GetString("HorizontalBellows", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Miech poziomy, zwany też miechem pudełkowym, ma kształt zamkniętego prostokątnego pudła z ruchomą górną płytą. Powietrze wtłaczane do wnętrza unosi płytę, a jej opadanie reguluje wypływ powietrza do wiatrownicy. Ciśnienie utrzymywane jest przez ciężary lub sprężyny. Miech ten dobrze sprawdza się jako magazyn powietrza w większych instrumentach..
        /// </summary>
        internal static string HorizontalBellowsDescription {
            get {
                return ResourceManager.GetString("HorizontalBellowsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Labialne metalowe.
        /// </summary>
        internal static string LabialMetal {
            get {
                return ResourceManager.GetString("LabialMetal", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Piszczałki wargowe metalowe to najczęściej spotykany typ piszczałek w organach, wykonane zazwyczaj ze stopu cyny i ołowiu, choć stosuje się także cynk, miedź czy aluminium. Ich działanie polega na przepuszczeniu powietrza przez szparę kierującą strumień na wargę (krawędź) piszczałki, co pobudza drgania słupa powietrza wewnątrz rurki – podobnie jak w fletni Pana. Metalowe piszczałki mają zazwyczaj okrągły przekrój i są dostępne w różnych formach: otwarte, kryte, stożkowe, cylindryczne itd. Charakteryzują się [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string LabialMetalDescription {
            get {
                return ResourceManager.GetString("LabialMetalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Labialne drewniane.
        /// </summary>
        internal static string LabialWooden {
            get {
                return ResourceManager.GetString("LabialWooden", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Piszczałki wargowe drewniane to rodzaj piszczałek organowych wykonanych głównie z drewna, takich jak sosna, dąb, klon czy mahoń. Działają na zasadzie przepływu powietrza przez szczelinę (szparę) i uderzenia o wargę piszczałki, co powoduje wibracje powietrza i powstanie dźwięku – podobnie jak w flecie prostym. Mają prostokątny przekrój i często budowane są w większych rozmiarach niż piszczałki metalowe, co pozwala im wydobywać głębokie, ciepłe brzmienia. Drewniane piszczałki wargowe stosowane są najczęściej  [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string LabialWoodenDescription {
            get {
                return ResourceManager.GetString("LabialWoodenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Duży.
        /// </summary>
        internal static string Large {
            get {
                return ResourceManager.GetString("Large", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Strona główna.
        /// </summary>
        internal static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Średni.
        /// </summary>
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Więcej.
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Traktura pneumatyczna.
        /// </summary>
        internal static string PneumaticAction {
            get {
                return ResourceManager.GetString("PneumaticAction", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Traktura pneumatyczna wykorzystuje sprężone powietrze do przekazywania sygnału z klawiatury do zaworów wiatrownicy. Naciśnięcie klawisza uruchamia mieszek lub zawór, który przesyła impuls powietrzny do odpowiedniego zaworu pod piszczałką. System ten pozwala oddalić stół gry od piszczałek i wymaga mniejszej siły przy grze, ale jest mniej precyzyjny, bardziej podatny na opóźnienia i wymaga częstszej konserwacji..
        /// </summary>
        internal static string PneumaticActionDescription {
            get {
                return ResourceManager.GetString("PneumaticActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Polityka prywatności.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Przycisk polityki prywatności.
        /// </summary>
        internal static string PrivacyPolicyButton {
            get {
                return ResourceManager.GetString("PrivacyPolicyButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kliknij, by przenieść się do strony polityki prywatności aplikacji.
        /// </summary>
        internal static string PrivacyPolicyButtonHelp {
            get {
                return ResourceManager.GetString("PrivacyPolicyButtonHelp", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Językowe.
        /// </summary>
        internal static string Reed {
            get {
                return ResourceManager.GetString("Reed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Piszczałki językowe (inaczej stroikowe) to typ piszczałek organowych, w których dźwięk powstaje poprzez drganie cienkiego metalowego języczka (stroika) osadzonego w mosiężnej rurce – zwanej kielichem (rezonatorem). Strumień powietrza wprawia języczek w wibracje, które następnie są wzmacniane i kształtowane przez rezonator. W przeciwieństwie do piszczałek wargowych, źródłem dźwięku nie jest cała kolumna powietrza, lecz drgający języczek. Piszczałki językowe mogą mieć rezonatory różnej długości, kształtu i ma [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string ReedDescription {
            get {
                return ResourceManager.GetString("ReedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wiatrownica rejestrowa.
        /// </summary>
        internal static string RegisterWindchest {
            get {
                return ResourceManager.GetString("RegisterWindchest", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wiatrownica rejestrowa to typ wiatrownicy, w której powietrze jest kierowane do grupy piszczałek zależnie od wybranego rejestru. Każdy rejestr (głos) ma swoją osobną sekcję wiatrownicy, z dedykowanymi zaworami dla każdej grupy piszczałek. W tym systemie zmiana rejestru polega na otwarciu lub zamknięciu odpowiednich klap w zależności od ustawionego głosu. Wiatrownice rejestrowe są stosowane w bardziej złożonych organach, umożliwiając dużą precyzję w zarządzaniu brzmieniem..
        /// </summary>
        internal static string RegisterWindchestDescription {
            get {
                return ResourceManager.GetString("RegisterWindchestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Szukaj....
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ustawienia.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Mały.
        /// </summary>
        internal static string Small {
            get {
                return ResourceManager.GetString("Small", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Piszczałki.
        /// </summary>
        internal static string Stops {
            get {
                return ResourceManager.GetString("Stops", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Piszczałki organowe to podstawowe źródło dźwięku w organach piszczałkowych. Każda piszczałka wydaje pojedynczy dźwięk i różni się długością, materiałem oraz konstrukcją, co wpływa na barwę i wysokość tonu. Piszczałki dzielą się na dwa główne typy: piszczałki wargowe (labialne), działające na zasadzie podobnej do fletu, oraz piszczałki stroikowe (języczkowe), w których dźwięk powstaje dzięki drgającemu języczkowi. Organy mogą zawierać od kilkuset do kilkudziesięciu tysięcy piszczałek, co pozwala na niezwykle [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string StopsDescription {
            get {
                return ResourceManager.GetString("StopsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rozmiar czcionki.
        /// </summary>
        internal static string TextSize {
            get {
                return ResourceManager.GetString("TextSize", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wiatrownica tonowa.
        /// </summary>
        internal static string ToneWindchest {
            get {
                return ResourceManager.GetString("ToneWindchest", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wiatrownica tonowa to typ wiatrownicy, w której powietrze jest kierowane do piszczałek z podziałem na poszczególne tony i rejestry. Każdy zestaw piszczałek posiada oddzielną sekcję wiatrownicy, z osobnymi klapami zaworowymi dla różnych głosów. Umożliwia to precyzyjne kontrolowanie poszczególnych rejestrów, a także lepszą kontrolę nad ciśnieniem powietrza. Tego typu wiatrownice stosowane są w bardziej zaawansowanych organach, oferując większą elastyczność w zakresie brzmienia..
        /// </summary>
        internal static string ToneWindchestDescription {
            get {
                return ResourceManager.GetString("ToneWindchestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Traktura mechaniczna.
        /// </summary>
        internal static string TrackerAction {
            get {
                return ResourceManager.GetString("TrackerAction", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Traktura mechaniczna (gryfowa) to system bezpośredniego połączenia klawiszy z zaworami wiatrownicy za pomocą cięgien, dźwigni i drążków. Naciśnięcie klawisza fizycznie otwiera zawór pod odpowiednią piszczałką, co umożliwia przepływ powietrza i wydobycie dźwięku. Zapewnia precyzyjne wyczucie gry i prostą konserwację, ale wymaga większej siły przy grze z wieloma głosami i jest trudna do zastosowania przy dużych odległościach między stołem gry a piszczałkami..
        /// </summary>
        internal static string TrackerActionDescription {
            get {
                return ResourceManager.GetString("TrackerActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wersja: 1.0.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Miech klinowy.
        /// </summary>
        internal static string WedgeBellows {
            get {
                return ResourceManager.GetString("WedgeBellows", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Miech klinowy składa się z dwóch drewnianych płyt połączonych skórą w kształcie klina. Górna płyta unosi się przy napełnianiu powietrzem i opada podczas jego oddawania. Jest to najstarszy typ miecha, dawniej obsługiwany ręcznie. Daje stabilne ciśnienie, ale ma ograniczoną pojemność i wymagał regularnego napełniania..
        /// </summary>
        internal static string WedgeBellowsDescription {
            get {
                return ResourceManager.GetString("WedgeBellowsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wiatrownice.
        /// </summary>
        internal static string Windchests {
            get {
                return ResourceManager.GetString("Windchests", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wiatrownica to kluczowy element mechanizmu organów piszczałkowych, odpowiedzialny za kierowanie powietrza do odpowiednich piszczałek. Znajduje się bezpośrednio pod zespołem piszczałek i działa jak swego rodzaju &quot;rozdzielnia powietrza&quot;. Wiatrownica zawiera szereg kanałów i zaworów, które otwierają się lub zamykają w zależności od naciśnięcia klawiszy i rejestrów przez organistę. Wyróżnia się różne typy wiatrownic, m.in. wiatrownice klapowo-zasuwowe (stosowane w organach mechanicznych), wiatrownice stożkowe ( [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string WindchestsDescription {
            get {
                return ResourceManager.GetString("WindchestsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Praca w toku.
        /// </summary>
        internal static string WIP {
            get {
                return ResourceManager.GetString("WIP", resourceCulture);
            }
        }
    }
}
